// TERAGON Business Graph — edge registry (Phase 2).
// The declarative catalogue of allowed typed relationships between entity types,
// covering the core-v1 spine (follow-up, printer/service, evidence paths,
// approved recommendations, generated tasks, learning/memory evidence) from
// EDGE_MAP §3. Metadata only — default provenance/authority reflect how each
// edge is physically derived (FK ⇒ DERIVED, join record ⇒ EXPLICIT, proposed ⇒
// UNVERIFIED). Not an index; no edges are materialized here.
import { z } from "zod";
import { graphEntityTypeSchema, type GraphEntityType } from "../contracts/identity";
import {
  graphAuthoritySchema,
  graphEdgeDirectionSchema,
  graphProvenanceSchema,
  graphRelationshipTypeSchema,
  type GraphAuthority,
  type GraphEdgeDirection,
  type GraphProvenance,
  type GraphRelationshipType,
} from "../contracts/edge";

export const EDGE_CARDINALITIES = ["1:1", "1:N", "N:1", "N:N"] as const;
export type EdgeCardinality = (typeof EDGE_CARDINALITIES)[number];
export const edgeCardinalitySchema = z.enum(EDGE_CARDINALITIES);

export interface EdgeRegistryEntry {
  relationshipType: GraphRelationshipType;
  sourceType: GraphEntityType;
  targetType: GraphEntityType;
  direction: GraphEdgeDirection;
  cardinality: EdgeCardinality;
  defaultProvenance: GraphProvenance;
  defaultAuthority: GraphAuthority;
  approvalGated: boolean;
  coreV1: boolean;
}

export const edgeRegistryEntrySchema = z.object({
  relationshipType: graphRelationshipTypeSchema,
  sourceType: graphEntityTypeSchema,
  targetType: graphEntityTypeSchema,
  direction: graphEdgeDirectionSchema,
  cardinality: edgeCardinalitySchema,
  defaultProvenance: graphProvenanceSchema,
  defaultAuthority: graphAuthoritySchema,
  approvalGated: z.boolean(),
  coreV1: z.boolean(),
}) satisfies z.ZodType<EdgeRegistryEntry>;

// Shorthands for the two dominant physical shapes.
const FK = "FOREIGN_KEY_DERIVED" as const;
const EXPLICIT = "EXPLICIT" as const;
const DERIVED = "DERIVED" as const;
const CANONICAL = "CANONICAL" as const;

export const EDGE_REGISTRY: readonly EdgeRegistryEntry[] = [
  // --- CRM / sales spine ---
  {
    relationshipType: "OWNS",
    sourceType: "organization",
    targetType: "customer",
    direction: "directed",
    cardinality: "1:N",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "CONTACT_FOR",
    sourceType: "contact",
    targetType: "customer",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "ASSIGNED_TO",
    sourceType: "lead",
    targetType: "user",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "DERIVED_FROM",
    sourceType: "opportunity",
    targetType: "lead",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "RELATED_TO",
    sourceType: "opportunity",
    targetType: "customer",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "QUOTED_FOR",
    sourceType: "quotation",
    targetType: "customer",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    // authoritative only when the quotation is approved (status "אושרה").
    approvalGated: true,
    coreV1: true,
  },
  {
    relationshipType: "USES",
    sourceType: "quotation",
    targetType: "product",
    direction: "directed",
    cardinality: "N:N",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "PURCHASED",
    sourceType: "customer",
    targetType: "product",
    direction: "directed",
    cardinality: "N:N",
    defaultProvenance: "INFERRED",
    defaultAuthority: "UNVERIFIED",
    approvalGated: false,
    coreV1: false,
  },
  // --- printers / service spine ---
  {
    relationshipType: "OWNS",
    sourceType: "customerPrinter",
    targetType: "customer",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "USES",
    sourceType: "customerPrinter",
    targetType: "printerModel",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "SERVICED",
    sourceType: "serviceTicket",
    targetType: "customer",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  // Phase 9 (core-v2) — the canonical ticket→printer link that lets recurrence be
  // grouped by (printerModel, faultCategory) through customerPrinter→printerModel.
  {
    relationshipType: "SERVICED",
    sourceType: "serviceTicket",
    targetType: "customerPrinter",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: false,
  },
  {
    relationshipType: "RESOLVED_BY",
    sourceType: "serviceTicket",
    targetType: "repairAction",
    direction: "directed",
    cardinality: "1:N",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  // --- learning / courses spine ---
  {
    relationshipType: "ASSIGNED_TO",
    sourceType: "course",
    targetType: "user",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "ENROLLED_IN",
    sourceType: "enrollment",
    targetType: "course",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: EXPLICIT,
    defaultAuthority: CANONICAL,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "RELATED_TO",
    sourceType: "enrollment",
    targetType: "student",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  // --- AI orchestration + evidence/approval spine ---
  {
    relationshipType: "RECOMMENDED",
    sourceType: "aiRecommendation",
    targetType: "agent",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "APPROVED_BY",
    sourceType: "aiRecommendation",
    targetType: "approval",
    direction: "directed",
    cardinality: "1:1",
    defaultProvenance: EXPLICIT,
    defaultAuthority: CANONICAL,
    // an approved recommendation is authoritative ONLY through a human approval.
    approvalGated: true,
    coreV1: true,
  },
  {
    relationshipType: "REJECTED_BY",
    sourceType: "aiRecommendation",
    targetType: "approval",
    direction: "directed",
    cardinality: "1:1",
    defaultProvenance: EXPLICIT,
    defaultAuthority: "REJECTED",
    approvalGated: true,
    coreV1: false,
  },
  {
    relationshipType: "GENERATED_TASK",
    sourceType: "agentRun",
    targetType: "task",
    direction: "directed",
    cardinality: "1:N",
    defaultProvenance: EXPLICIT,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  // Phase 9 (core-v2) — the canonical recommendation→task link (from
  // Task.sourceRecommendationId) so an approved recommendation walks to the task
  // it generated. rec↔task is NEVER matched by title/text.
  {
    relationshipType: "GENERATED_TASK",
    sourceType: "aiRecommendation",
    targetType: "task",
    direction: "directed",
    cardinality: "1:N",
    defaultProvenance: EXPLICIT,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: false,
  },
  {
    relationshipType: "ASSIGNED_TO",
    sourceType: "task",
    targetType: "user",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "SUPPORTED_BY",
    sourceType: "aiRecommendation",
    targetType: "knowledgeArticle",
    direction: "directed",
    cardinality: "N:N",
    defaultProvenance: "INFERRED",
    defaultAuthority: "UNVERIFIED",
    approvalGated: false,
    coreV1: true,
  },
  // --- memory / knowledge / learning evidence + lineage ---
  {
    relationshipType: "MENTIONED_IN",
    sourceType: "memoryRecord",
    targetType: "customer",
    direction: "directed",
    cardinality: "N:N",
    defaultProvenance: EXPLICIT,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "SUPERSEDES",
    sourceType: "memoryRecord",
    targetType: "memoryRecord",
    direction: "directed",
    cardinality: "1:1",
    defaultProvenance: FK,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "CONTRADICTS",
    sourceType: "memoryRecord",
    targetType: "memoryRecord",
    direction: "bidirectional",
    cardinality: "N:N",
    defaultProvenance: EXPLICIT,
    defaultAuthority: "UNVERIFIED",
    approvalGated: false,
    coreV1: false,
  },
  {
    relationshipType: "VERSION_OF",
    sourceType: "knowledgeArticle",
    targetType: "knowledgeArticle",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: EXPLICIT,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: false,
  },
  {
    relationshipType: "DERIVED_FROM",
    sourceType: "learningRule",
    targetType: "learningProposal",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: EXPLICIT,
    defaultAuthority: DERIVED,
    approvalGated: true,
    coreV1: true,
  },
  {
    relationshipType: "SUPPORTED_BY",
    sourceType: "learningProposal",
    targetType: "memoryRecord",
    direction: "directed",
    cardinality: "N:N",
    defaultProvenance: "INFERRED",
    defaultAuthority: "UNVERIFIED",
    approvalGated: false,
    coreV1: true,
  },
  // --- governance / audit ---
  {
    relationshipType: "AUDITS",
    sourceType: "auditEvent",
    targetType: "customer",
    direction: "directed",
    cardinality: "N:1",
    defaultProvenance: EXPLICIT,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: true,
  },
  {
    relationshipType: "RELATED_TO",
    sourceType: "governancePolicy",
    targetType: "agent",
    direction: "directed",
    cardinality: "N:N",
    defaultProvenance: "INFERRED",
    defaultAuthority: "UNVERIFIED",
    approvalGated: false,
    coreV1: false,
  },
  {
    relationshipType: "CREATED",
    sourceType: "agentRun",
    targetType: "aiRecommendation",
    direction: "directed",
    cardinality: "1:N",
    defaultProvenance: EXPLICIT,
    defaultAuthority: DERIVED,
    approvalGated: false,
    coreV1: false,
  },
] as const;
