// Seed boot path: map every collection to its deterministic demo dataset and
// seed only the collections that are still empty (first run / after reset).
import type { BaseEntity } from "@/domain/types";
import type { CollectionKey } from "../collections";
import {
  ACTIVITIES,
  AGENT_CONFLICTS,
  AGENT_HANDOFFS,
  AGENT_MESSAGES,
  AGENT_TASKS,
  AGENTS,
  AI_RECOMMENDATIONS,
  APPROVALS,
  ASSIGNMENTS,
  AUDIT_EVENTS,
  AUTOMATION_RUNS,
  AUTOMATIONS,
  CONTACTS,
  CONTROLS,
  COURSE_SESSIONS,
  COURSES,
  CUSTOMER_PRINTERS,
  CUSTOMERS,
  DOCUMENTS,
  ENROLLMENTS,
  EVIDENCE,
  IMPLEMENTATION_STAGES,
  KNOWLEDGE_NOTES,
  LEADS,
  LEARNING_PATHS,
  MEETINGS,
  MEMORY_RECORDS,
  METRIC_DEFINITIONS,
  METRIC_OBSERVATIONS,
  OPPORTUNITIES,
  ORGANIZATIONS,
  PERSONAS,
  PRINTER_MODELS,
  PRODUCTS,
  QUOTATIONS,
  REPAIR_ACTIONS,
  RISKS,
  ROLES,
  SERVICE_TICKETS,
  STAGE_GATES,
  STUDENTS,
  SUPPORT_REQUESTS,
  TASKS,
  TRAINING_MATERIALS,
  USERS,
} from "./seedData";

export * from "./seedData";

// S13.4 (PR D) — deterministic synthetic seed for the real local-memory CRUD.
// Org-scoped ("org-1"); no real business/customer data. Fixed timestamps (no random).
import type { MemoryEntry } from "@/domain/memory/entry";
const MEMORY_ENTRIES_SEED: readonly MemoryEntry[] = [
  {
    id: "me-1", createdAt: "2026-07-01T09:00:00.000Z", updatedAt: "2026-07-01T09:00:00.000Z",
    organizationId: "org-1", title: "מדיניות מצב הדגמה", category: "PROCESS", status: "ACTIVE",
    source: "user", tags: ["דמו", "מדיניות"],
    content: "כל הנתונים כאן סינתטיים. אין להזין נתוני לקוח אמיתיים במצב ההדגמה.",
  },
  {
    id: "me-2", createdAt: "2026-07-03T11:30:00.000Z", updatedAt: "2026-07-05T08:15:00.000Z",
    organizationId: "org-1", title: "החלטה: אישור אנושי לכל כתיבה", category: "DECISION", status: "ACTIVE",
    source: "user", tags: ["אישורים", "ממשל"],
    content: "כל שינוי שמבצע סוכן מחייב אישור אנושי מפורש דרך מנוע האישורים.",
  },
  {
    id: "me-3", createdAt: "2026-07-10T14:00:00.000Z", updatedAt: "2026-07-10T14:00:00.000Z",
    organizationId: "org-1", title: "לקח: השלמת פרטי לקוח מוקדם", category: "LEARNING", status: "ARCHIVED",
    source: "user", tags: ["לקוחות", "איכות-נתונים"],
    content: "רשומות לקוח חסרות פוגעות במעקב ובפילוח — כדאי להשלים שדות חובה מוקדם.",
  },
] as const;

/** collection → deterministic seed items */
export const SEED: Record<CollectionKey, readonly BaseEntity[]> = {
  organizations: ORGANIZATIONS,
  users: USERS,
  roles: ROLES,
  customers: CUSTOMERS,
  contacts: CONTACTS,
  leads: LEADS,
  opportunities: OPPORTUNITIES,
  quotations: QUOTATIONS,
  products: PRODUCTS,
  printerModels: PRINTER_MODELS,
  customerPrinters: CUSTOMER_PRINTERS,
  courses: COURSES,
  learningPaths: LEARNING_PATHS,
  students: STUDENTS,
  enrollments: ENROLLMENTS,
  courseSessions: COURSE_SESSIONS,
  assignments: ASSIGNMENTS,
  serviceTickets: SERVICE_TICKETS,
  repairActions: REPAIR_ACTIONS,
  tasks: TASKS,
  meetings: MEETINGS,
  activities: ACTIVITIES,
  documents: DOCUMENTS,
  knowledgeNotes: KNOWLEDGE_NOTES,
  memoryRecords: MEMORY_RECORDS,
  automations: AUTOMATIONS,
  automationRuns: AUTOMATION_RUNS,
  agents: AGENTS,
  agentTasks: AGENT_TASKS,
  agentMessages: AGENT_MESSAGES,
  agentHandoffs: AGENT_HANDOFFS,
  agentConflicts: AGENT_CONFLICTS,
  // Wave 5 orchestration collections — derived at runtime, never seeded
  agentRuns: [],
  agentEvents: [],
  agentErrors: [],
  // Wave 6 governance collections — created by workflows, never seeded
  memoryProposals: [],
  memorySources: [],
  memoryLinks: [],
  memoryVersions: [],
  memoryUsage: [],
  memoryConflicts: [],
  memoryImportJobs: [],
  memoryExportJobs: [],
  memoryEntries: MEMORY_ENTRIES_SEED,
  knowledgeArticles: [],
  knowledgeSources: [],
  knowledgeVersions: [],
  knowledgeUsage: [],
  knowledgeConflicts: [],
  knowledgeQuestions: [],
  knowledgeReviews: [],
  learningObservations: [],
  recommendationOutcomes: [],
  learningProposals: [],
  learningEvidence: [],
  learningRules: [],
  learningRuleVersions: [],
  learningRollbacks: [],
  // Wave 7 — created by workflows/content bootstrap, never seeded here
  implementationProgrammes: [],
  implementationMilestones: [],
  implementationRisks: [],
  implementationEvidence: [],
  implementationDecisions: [],
  rolloutWaves: [],
  pilotDefinitions: [],
  pilotResults: [],
  submissionPackages: [],
  submissionDeliverables: [],
  submissionEvidence: [],
  submissionValidations: [],
  submissionBlockers: [],
  submissionSnapshots: [],
  presentationSections: [],
  presenterNotes: [],
  demoSteps: [],
  qualityValidations: [],
  objections: [],
  // Wave 8 — created by workflows, never seeded
  reportDefinitions: [],
  reportRuns: [],
  metricAlerts: [],
  analyticsViews: [],
  governancePolicies: [],
  governancePolicyVersions: [],
  governanceRisks: [],
  governanceIncidents: [],
  governanceReviews: [],
  promptVersions: [],
  accessChangeRequests: [],
  accessReviews: [],
  healthSnapshots: [],
  meta: [],
  aiRecommendations: AI_RECOMMENDATIONS,
  evidence: EVIDENCE,
  approvals: APPROVALS,
  auditEvents: AUDIT_EVENTS,
  metricDefinitions: METRIC_DEFINITIONS,
  metricObservations: METRIC_OBSERVATIONS,
  risks: RISKS,
  controls: CONTROLS,
  personas: PERSONAS,
  trainingMaterials: TRAINING_MATERIALS,
  implementationStages: IMPLEMENTATION_STAGES,
  stageGates: STAGE_GATES,
  supportRequests: SUPPORT_REQUESTS,
  // notifications are DERIVED at boot from real repository conditions
  // (src/app/notifications/deriveNotifications.ts) — never seeded with fixed data.
  notifications: [],
} as const;
