// Seed boot path: map every collection to its deterministic demo dataset and
// seed only the collections that are still empty (first run / after reset).
import type { BaseEntity } from "@/domain/types";
import type { CollectionKey } from "../collections";
import {
  ACTIVITIES,
  AGENT_CONFLICTS,
  AGENT_HANDOFFS,
  AGENT_MESSAGES,
  AGENT_TASKS,
  AGENTS,
  AI_RECOMMENDATIONS,
  APPROVALS,
  ASSIGNMENTS,
  AUDIT_EVENTS,
  AUTOMATION_RUNS,
  AUTOMATIONS,
  CONTACTS,
  CONTROLS,
  COURSE_SESSIONS,
  COURSES,
  CUSTOMER_PRINTERS,
  CUSTOMERS,
  DOCUMENTS,
  ENROLLMENTS,
  EVIDENCE,
  IMPLEMENTATION_STAGES,
  KNOWLEDGE_NOTES,
  LEADS,
  LEARNING_PATHS,
  MEETINGS,
  MEMORY_RECORDS,
  METRIC_DEFINITIONS,
  METRIC_OBSERVATIONS,
  OPPORTUNITIES,
  ORGANIZATIONS,
  PERSONAS,
  PRINTER_MODELS,
  PRODUCTS,
  QUOTATIONS,
  REPAIR_ACTIONS,
  RISKS,
  ROLES,
  SERVICE_TICKETS,
  STAGE_GATES,
  STUDENTS,
  SUPPORT_REQUESTS,
  TASKS,
  TRAINING_MATERIALS,
  USERS,
} from "./seedData";

export * from "./seedData";

/** collection → deterministic seed items */
export const SEED: Record<CollectionKey, readonly BaseEntity[]> = {
  organizations: ORGANIZATIONS,
  users: USERS,
  roles: ROLES,
  customers: CUSTOMERS,
  contacts: CONTACTS,
  leads: LEADS,
  opportunities: OPPORTUNITIES,
  quotations: QUOTATIONS,
  products: PRODUCTS,
  printerModels: PRINTER_MODELS,
  customerPrinters: CUSTOMER_PRINTERS,
  courses: COURSES,
  learningPaths: LEARNING_PATHS,
  students: STUDENTS,
  enrollments: ENROLLMENTS,
  courseSessions: COURSE_SESSIONS,
  assignments: ASSIGNMENTS,
  serviceTickets: SERVICE_TICKETS,
  repairActions: REPAIR_ACTIONS,
  tasks: TASKS,
  meetings: MEETINGS,
  activities: ACTIVITIES,
  documents: DOCUMENTS,
  knowledgeNotes: KNOWLEDGE_NOTES,
  memoryRecords: MEMORY_RECORDS,
  automations: AUTOMATIONS,
  automationRuns: AUTOMATION_RUNS,
  agents: AGENTS,
  agentTasks: AGENT_TASKS,
  agentMessages: AGENT_MESSAGES,
  agentHandoffs: AGENT_HANDOFFS,
  agentConflicts: AGENT_CONFLICTS,
  // Wave 5 orchestration collections — derived at runtime, never seeded
  agentRuns: [],
  agentEvents: [],
  agentErrors: [],
  aiRecommendations: AI_RECOMMENDATIONS,
  evidence: EVIDENCE,
  approvals: APPROVALS,
  auditEvents: AUDIT_EVENTS,
  metricDefinitions: METRIC_DEFINITIONS,
  metricObservations: METRIC_OBSERVATIONS,
  risks: RISKS,
  controls: CONTROLS,
  personas: PERSONAS,
  trainingMaterials: TRAINING_MATERIALS,
  implementationStages: IMPLEMENTATION_STAGES,
  stageGates: STAGE_GATES,
  supportRequests: SUPPORT_REQUESTS,
  // notifications are DERIVED at boot from real repository conditions
  // (src/app/notifications/deriveNotifications.ts) — never seeded with fixed data.
  notifications: [],
} as const;
