// Canonical collection registry — the IndexedDB schema (one object store per
// collection) and the repository factory both derive from this single list.

export const COLLECTIONS = [
  "organizations",
  "users",
  "roles",
  "customers",
  "contacts",
  "leads",
  "opportunities",
  "quotations",
  "products",
  "printerModels",
  "customerPrinters",
  "courses",
  "learningPaths",
  "students",
  "enrollments",
  "courseSessions",
  "assignments",
  "serviceTickets",
  "repairActions",
  "tasks",
  "meetings",
  "activities",
  "documents",
  "knowledgeNotes",
  // Wave 6 — knowledge governance
  "knowledgeArticles",
  "knowledgeSources",
  "knowledgeVersions",
  "knowledgeUsage",
  "knowledgeConflicts",
  "knowledgeQuestions",
  "knowledgeReviews",
  "memoryRecords",
  // Wave 6 — memory governance
  "memoryProposals",
  "memorySources",
  "memoryLinks",
  "memoryVersions",
  "memoryUsage",
  "memoryConflicts",
  "memoryImportJobs",
  "memoryExportJobs",
  "automations",
  "automationRuns",
  "agents",
  "agentTasks",
  "agentMessages",
  "agentHandoffs",
  "agentConflicts",
  "agentRuns",
  "agentEvents",
  "agentErrors",
  "aiRecommendations",
  "evidence",
  "approvals",
  "auditEvents",
  "metricDefinitions",
  "metricObservations",
  "risks",
  "controls",
  "personas",
  "trainingMaterials",
  "implementationStages",
  "stageGates",
  "supportRequests",
  "notifications",
  // Wave 6 — governed learning
  "learningObservations",
  "recommendationOutcomes",
  "learningProposals",
  "learningEvidence",
  "learningRules",
  "learningRuleVersions",
  "learningRollbacks",
  // Wave 7 — adoption programme
  "implementationProgrammes",
  "implementationMilestones",
  "implementationRisks",
  "implementationEvidence",
  "implementationDecisions",
  "rolloutWaves",
  "pilotDefinitions",
  "pilotResults",
  // Wave 7 — submission & presentation
  "submissionPackages",
  "submissionDeliverables",
  "submissionEvidence",
  "submissionValidations",
  "submissionBlockers",
  "submissionSnapshots",
  "presentationSections",
  "presenterNotes",
  "demoSteps",
  "qualityValidations",
  "objections",
  // Wave 6 — schema meta (migration bookkeeping)
  "meta",
] as const;

export type CollectionKey = (typeof COLLECTIONS)[number];

export function isCollectionKey(value: string): value is CollectionKey {
  return (COLLECTIONS as readonly string[]).includes(value);
}
