// W8-A — the canonical /analytics metric catalogue: 6 mandated groups.
// CONSUMES (bridges) W7-E's SUBMISSION_METRICS typing — never re-invents it.
// Every מחושב metric names its real collections; every unmeasured metric says
// honestly WHY it cannot be measured (no telemetry, no linkage, no survey).
import type { AnalyticsMetricDef } from "@/domain/analytics";

export const ANALYTICS_ENGINE_VERSION = "w8a-1.0";

export const ANALYTICS_METRICS: readonly AnalyticsMetricDef[] = [
  // ========================================================================
  // א — פעילות והטמעה
  // ========================================================================
  {
    key: "activities_count",
    titleHe: "פעילויות מתועדות",
    group: "א",
    unit: "פעילויות",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף activities — פיד הפעילות האמיתי",
    sourceCollections: ["activities"],
    calculationMethodHe: "ספירת רשומות activities עם at בתוך התקופה",
    limitationsHe: ["פעולות שלא תועדו במערכת אינן נספרות"],
    ownerId: "u-noa",
    seedMetricId: null,
    submissionKey: null,
    entityType: "activity",
  },
  {
    key: "knowledge_usage_count",
    titleHe: "שימושי מאגר הידע (כראיה)",
    group: "א",
    unit: "שימושים",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף knowledgeUsage — כל שימוש מתועד של מאמר בתוך המלצה",
    sourceCollections: ["knowledgeUsage"],
    calculationMethodHe: "ספירת רשומות knowledgeUsage עם usedAt בתוך התקופה",
    limitationsHe: ["נספר רק שימוש כראיה בהמלצות — לא צפיות אנושיות (אין טלמטריית צפייה)"],
    ownerId: "u-noa",
    seedMetricId: null,
    submissionKey: null,
    entityType: "knowledgeUsage",
  },
  {
    key: "memory_usage_count",
    titleHe: "שימושי הזיכרון הארגוני",
    group: "א",
    unit: "שימושים",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף memoryUsage — איזו גרסת זיכרון שימשה איזו תשובה",
    sourceCollections: ["memoryUsage"],
    calculationMethodHe: "ספירת רשומות memoryUsage עם usedAt בתוך התקופה",
    limitationsHe: ["נספר רק שימוש על ידי מעטפות AI — לא עיון אנושי"],
    ownerId: "u-noa",
    seedMetricId: null,
    submissionKey: null,
    entityType: "memoryUsage",
  },
  {
    key: "support_volume",
    titleHe: "פניות תמיכה שנפתחו",
    group: "א",
    unit: "פניות",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף supportRequests — מערכת התמיכה החיה (/support)",
    sourceCollections: ["supportRequests"],
    calculationMethodHe: "ספירת supportRequests עם createdAt בתוך התקופה",
    limitationsHe: ["ללא קו בסיס לפני-הדרכה אי אפשר לקבוע ירידה"],
    ownerId: "u-ran",
    seedMetricId: null,
    submissionKey: "support_volume",
    entityType: "supportRequest",
  },
  {
    key: "wau",
    titleHe: "משתמשים פעילים שבועיים (WAU)",
    group: "א",
    unit: "%",
    betterWhen: "higher",
    kind: "מבני",
    temporality: "snapshot",
    sourceHe: "אין טלמטריית שימוש באפליקציה המקומית — מוגדר אך לא נמדד",
    sourceCollections: [],
    calculationMethodHe: "משתמשים פעילים בשבוע ÷ משתמשים מוגדרים × 100",
    limitationsHe: ["המערכת רצה מקומית ללא איסוף אירועי שימוש — נדרשת החלטת ממשל לפני טלמטריה"],
    ownerId: "u-tzachi",
    seedMetricId: null,
    submissionKey: "wau",
    entityType: null,
  },
  {
    key: "repeat_usage",
    titleHe: "שימוש חוזר (משתמש/שבוע)",
    group: "א",
    unit: "שימושים",
    betterWhen: "higher",
    kind: "מבני",
    temporality: "snapshot",
    sourceHe: "אין טלמטריית שימוש — מוגדר בלבד",
    sourceCollections: [],
    calculationMethodHe: "מספר כניסות משתמש בשבוע — ללא מקור נתונים",
    limitationsHe: ["ללא איסוף אירועים אין דרך כנה למדוד — לא מוצג מספר"],
    ownerId: "u-tzachi",
    seedMetricId: null,
    submissionKey: "repeat_usage",
    entityType: null,
  },

  // ========================================================================
  // ב — מכירות ולקוחות
  // ========================================================================
  {
    key: "leads_new",
    titleHe: "לידים חדשים",
    group: "ב",
    unit: "לידים",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף leads — לפי createdAt",
    sourceCollections: ["leads"],
    calculationMethodHe: "ספירת לידים שנוצרו בתוך התקופה",
    limitationsHe: [],
    ownerId: "u-maya",
    seedMetricId: "md-2",
    submissionKey: null,
    entityType: "lead",
  },
  {
    key: "lead_first_response_hours",
    titleHe: "זמן תגובה ראשונה לליד",
    group: "ב",
    unit: "שעות",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף activities (entityRef=lead:*) מול אוסף leads",
    sourceCollections: ["activities", "leads"],
    calculationMethodHe:
      "חציון (זמן פעילות ראשונה − זמן יצירת הליד) על לידים שנוצרו בתקופה ויש להם פעילות תגובה",
    limitationsHe: ["פעילויות שלא תועדו (טלפון/וואטסאפ ישיר) אינן נספרות — המדד מוטה כלפי מעלה"],
    ownerId: "u-maya",
    seedMetricId: null,
    submissionKey: "lead_response_hours",
    entityType: "lead",
  },
  {
    key: "quotations_created",
    titleHe: "הצעות מחיר שנוצרו",
    group: "ב",
    unit: "הצעות",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף quotations — לפי createdAt",
    sourceCollections: ["quotations"],
    calculationMethodHe: "ספירת הצעות מחיר שנוצרו בתוך התקופה",
    limitationsHe: [],
    ownerId: "u-maya",
    seedMetricId: null,
    submissionKey: null,
    entityType: "quotation",
  },
  {
    key: "quotation_conversion",
    titleHe: "שיעור המרת הצעות מחיר (מצטבר)",
    group: "ב",
    unit: "%",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "אוסף quotations — הצעות שהוכרעו (אושרה/נדחתה/פג תוקף)",
    sourceCollections: ["quotations"],
    calculationMethodHe: 'הצעות "אושרה" ÷ הצעות שהוכרעו × 100',
    limitationsHe: ["הצעות פתוחות (טיוטה/נשלחה) אינן במונה ואינן במכנה", "אין תיעוד מועד הכרעה — מדד מצטבר בלבד"],
    ownerId: "u-maya",
    seedMetricId: null,
    submissionKey: "quotation_conversion",
    entityType: "quotation",
  },
  {
    key: "pipeline_value",
    titleHe: "שווי צבר מכירות פתוח",
    group: "ב",
    unit: "₪",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "selectors/revenuePipeline — הצעות טיוטה/נשלחה אחרי הנחה",
    sourceCollections: ["quotations"],
    calculationMethodHe: "סכום הצעות פתוחות (טיוטה/נשלחה) אחרי הנחה",
    limitationsHe: [],
    ownerId: "u-maya",
    seedMetricId: "md-1",
    submissionKey: null,
    entityType: "quotation",
  },

  // ========================================================================
  // ג — שירות ותפעול
  // ========================================================================
  {
    key: "service_resolution_days",
    titleHe: "זמן פתרון קריאת שירות",
    group: "ג",
    unit: "ימים",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף serviceTickets — קריאות עם closedAt (הגירה m007)",
    sourceCollections: ["serviceTickets"],
    calculationMethodHe: "חציון (closedAt − openedAt) על קריאות שנסגרו בתוך התקופה",
    limitationsHe: ["קריאות סגורות ללא closedAt אינן נספרות"],
    ownerId: "u-ran",
    seedMetricId: null,
    submissionKey: "service_resolution_days",
    entityType: "serviceTicket",
  },
  {
    key: "sla_breaches",
    titleHe: "חריגות SLA בתמיכה (כעת)",
    group: "ג",
    unit: "פניות",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "אוסף supportRequests + supportSla (modules/support/lib)",
    sourceCollections: ["supportRequests"],
    calculationMethodHe: 'ספירת פניות פתוחות שמצב ה-SLA שלהן "חריגה" ברגע החישוב',
    limitationsHe: ["תמונת-רגע — אין היסטוריית חריגות שמורה"],
    ownerId: "u-ran",
    seedMetricId: null,
    submissionKey: null,
    entityType: "supportRequest",
  },
  {
    key: "tasks_overdue",
    titleHe: "משימות באיחור (כעת)",
    group: "ג",
    unit: "משימות",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "אוסף tasks + selectors/badges·isOverdueTask",
    sourceCollections: ["tasks"],
    calculationMethodHe: "ספירת משימות פתוחות שתאריך היעד שלהן חלף (סוף יום)",
    limitationsHe: ["תמונת-רגע — משימות שאוחרו ונסגרו אינן נספרות"],
    ownerId: "u-tzachi",
    seedMetricId: null,
    submissionKey: null,
    entityType: "task",
  },
  {
    key: "escalation_rate",
    titleHe: "שיעור אסקלציות (Tier 2+)",
    group: "ג",
    unit: "%",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "אוסף supportRequests — שדה tier (m002)",
    sourceCollections: ["supportRequests"],
    calculationMethodHe: "פניות ב-Tier ≥ 2 ÷ כלל הפניות × 100",
    limitationsHe: ["רשומות ישנות ללא שדה tier מסווגות לפי סימוני ⟦Tier⟧ במלל"],
    ownerId: "u-ran",
    seedMetricId: null,
    submissionKey: "escalation_rate",
    entityType: "supportRequest",
  },
  {
    key: "open_tickets",
    titleHe: "קריאות שירות פתוחות (כעת)",
    group: "ג",
    unit: "קריאות",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "selectors/openTickets — קריאות שאינן טופל/נסגר",
    sourceCollections: ["serviceTickets"],
    calculationMethodHe: 'ספירת קריאות שאינן בסטטוס "טופל"/"נסגר"',
    limitationsHe: [],
    ownerId: "u-ran",
    seedMetricId: "md-4",
    submissionKey: null,
    entityType: "serviceTicket",
  },

  // ========================================================================
  // ד — הדרכה ולמידה
  // ========================================================================
  {
    key: "enrollment_progress",
    titleHe: "השלמת שלבי למידה (תלמידים)",
    group: "ד",
    unit: "%",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "selectors/dashboardKpis·courseCompletion — אוסף enrollments",
    sourceCollections: ["enrollments"],
    calculationMethodHe: "שלבים שאושרו ÷ סך השלבים × 100",
    limitationsHe: ["מודד את תלמידי הקורסים — לא את הדרכת צוות טרגון"],
    ownerId: "u-oren",
    seedMetricId: "md-5",
    submissionKey: "course_completion",
    entityType: "enrollment",
  },
  {
    key: "training_completion",
    titleHe: "השלמת מסלולי הדרכה (צוות)",
    group: "ד",
    unit: "%",
    betterWhen: "higher",
    kind: "יעד פיילוט",
    temporality: "snapshot",
    sourceHe: "רישום ידני במפגשי ההדרכה — ההדרכה טרם התקיימה",
    sourceCollections: [],
    calculationMethodHe: "משתתפים שהשלימו ÷ משתתפי הפיילוט × 100",
    limitationsHe: ["אין עדיין מפגשי הדרכה — המדידה תחל עם תחילת ההדרכות"],
    ownerId: "u-oren",
    seedMetricId: null,
    submissionKey: "training_completion",
    entityType: null,
  },
  {
    key: "knowledge_check",
    titleHe: "בדיקת ידע (Knowledge Check)",
    group: "ד",
    unit: "%",
    betterWhen: "higher",
    kind: "מבני",
    temporality: "snapshot",
    sourceHe: "שאלון בסוף מפגש — טרם נבנה שאלון",
    sourceCollections: [],
    calculationMethodHe: "ציון שאלון הבנה בסוף כל מפגש — אין שאלון ואין נתונים",
    limitationsHe: ["מדד מבני — יופעל עם ההדרכה הראשונה"],
    ownerId: "u-oren",
    seedMetricId: null,
    submissionKey: "knowledge_check",
    entityType: null,
  },
  {
    key: "training_satisfaction",
    titleHe: "שביעות רצון מההדרכה",
    group: "ד",
    unit: "ציון",
    betterWhen: "higher",
    kind: "יעד פיילוט",
    temporality: "snapshot",
    sourceHe: "סקר סוף-מפגש — טרם הועבר",
    sourceCollections: [],
    calculationMethodHe: "ממוצע ציוני סקר 1-5",
    limitationsHe: ["אין נתוני סקר — ההדרכות טרם התקיימו"],
    ownerId: "u-oren",
    seedMetricId: null,
    submissionKey: "training_satisfaction",
    entityType: null,
  },

  // ========================================================================
  // ה — AI וממשל
  // ========================================================================
  {
    key: "rec_approved_rate",
    titleHe: "שיעור המלצות שאושרו",
    group: "ה",
    unit: "%",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "אוסף approvals — רשומות אישור אמיתיות",
    sourceCollections: ["approvals"],
    calculationMethodHe: 'אישורים בסטטוס "אושר" ÷ אישורים שהוכרעו × 100',
    limitationsHe: ["מדגם קטן בשלב זה — המספר ישתנה משמעותית עם השימוש"],
    ownerId: "u-tzachi",
    seedMetricId: "md-7",
    submissionKey: "rec_approved_rate",
    entityType: "approval",
  },
  {
    key: "rec_edited_rate",
    titleHe: "שיעור המלצות שנערכו לפני אישור",
    group: "ה",
    unit: "%",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "אוסף approvals — שדה extendedState (m005)",
    sourceCollections: ["approvals"],
    calculationMethodHe: 'אישורים במצב מורחב "edited" ÷ אישורים שהוכרעו × 100',
    limitationsHe: ['רשומות ללא extendedState אינן נספרות כ"נערכו" — ייתכן תת-דיווח'],
    ownerId: "u-tzachi",
    seedMetricId: null,
    submissionKey: "rec_edited_rate",
    entityType: "approval",
  },
  {
    key: "rec_rejected_rate",
    titleHe: "שיעור המלצות שנדחו",
    group: "ה",
    unit: "%",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "אוסף approvals — רשומות אישור אמיתיות",
    sourceCollections: ["approvals"],
    calculationMethodHe: 'אישורים בסטטוס "נדחה" ÷ אישורים שהוכרעו × 100',
    limitationsHe: ["מדגם קטן בשלב זה"],
    ownerId: "u-tzachi",
    seedMetricId: null,
    submissionKey: "rec_rejected_rate",
    entityType: "approval",
  },
  {
    key: "ai_runs_count",
    titleHe: "ריצות סוכנים מקומיות",
    group: "ה",
    unit: "ריצות",
    betterWhen: "none",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף agentRuns — מנוע התזמור המקומי (Mode A)",
    sourceCollections: ["agentRuns"],
    calculationMethodHe: "ספירת agentRuns עם startedAt בתוך התקופה",
    limitationsHe: ["Mode A מקומי — usageSpentILS מדוד = 0; ריצות הדגמה מסומנות demo"],
    ownerId: "u-noa",
    seedMetricId: null,
    submissionKey: null,
    entityType: "agentRun",
  },
  {
    key: "ai_recommendations_count",
    titleHe: "המלצות AI שנוצרו",
    group: "ה",
    unit: "המלצות",
    betterWhen: "none",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף aiRecommendations",
    sourceCollections: ["aiRecommendations"],
    calculationMethodHe: "ספירת aiRecommendations עם createdAt בתוך התקופה",
    limitationsHe: ["confidenceMethod null בהמלצות = ביטחון שלא נמדד — לא מוצג מספר ביטחון"],
    ownerId: "u-noa",
    seedMetricId: null,
    submissionKey: null,
    entityType: "aiRecommendation",
  },
  {
    key: "ai_fallbacks",
    titleHe: "מעברי fallback למנוע המקומי",
    group: "ה",
    unit: "אירועים",
    betterWhen: "lower",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף auditEvents — פעולות שמתעדות מעבר ספק",
    sourceCollections: ["auditEvents"],
    calculationMethodHe:
      'ספירת אירועי audit שה-action שלהם "ai.fallback" או שהפירוט מכיל "מנוע המקומי"',
    limitationsHe: [
      "כיום אין רשומת audit ייעודית ל-fallback (הגילוי הוא נתון בתוך המעטפה) — ספירה כנה של 0 עד שיתווסף תיעוד",
    ],
    ownerId: "u-noa",
    seedMetricId: null,
    submissionKey: null,
    entityType: "auditEvent",
  },
  {
    key: "automation_success",
    titleHe: "הצלחת אוטומציות",
    group: "ה",
    unit: "%",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "selectors/automationSuccessRate — אוספי automations + automationRuns",
    sourceCollections: ["automations", "automationRuns"],
    calculationMethodHe: "ריצות שהסתיימו בהצלחה ÷ ריצות שהסתיימו × 100",
    limitationsHe: ["מדגם קטן (ריצות מתועדות בודדות)"],
    ownerId: "u-noa",
    seedMetricId: "md-9",
    submissionKey: null,
    entityType: "automationRun",
  },

  // ========================================================================
  // ו — תוצאות עסקיות
  // ========================================================================
  {
    key: "approved_revenue",
    titleHe: "שווי הצעות שאושרו",
    group: "ו",
    unit: "₪",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "series",
    sourceHe: "אוסף quotations — הצעות בסטטוס אושרה",
    sourceCollections: ["quotations"],
    calculationMethodHe: "סכום (אחרי הנחה) של הצעות שאושרו, משויכות לתקופה לפי updatedAt",
    limitationsHe: ["אין שדה מועד-אישור — updatedAt משמש קירוב למועד ההכרעה"],
    ownerId: "u-maya",
    seedMetricId: null,
    submissionKey: null,
    entityType: "quotation",
  },
  {
    key: "revenue_total",
    titleHe: "הכנסות מצטברות (לקוחות)",
    group: "ו",
    unit: "₪",
    betterWhen: "higher",
    kind: "מחושב",
    temporality: "snapshot",
    sourceHe: "selectors/totalRevenue — אוסף customers",
    sourceCollections: ["customers"],
    calculationMethodHe: "סכום שדה revenue של כל הלקוחות",
    limitationsHe: ["שדה מצטבר ידני — חייב להתלכד עם הצעות שאושרו (בדיקת עקביות נפרדת)"],
    ownerId: "u-tzachi",
    seedMetricId: "md-3",
    submissionKey: null,
    entityType: "customer",
  },
  {
    key: "nps",
    titleHe: "NPS לקוחות",
    group: "ו",
    unit: "נק'",
    betterWhen: "higher",
    kind: "יעד פיילוט",
    temporality: "snapshot",
    sourceHe: "סקר לקוחות — טרם הועבר; קו בסיס טרם נמדד",
    sourceCollections: [],
    calculationMethodHe: "% ממליצים − % מסתייגים (מוסכמת ‎-100..+100)",
    limitationsHe: ["אין נתוני סקר — לא מוצג מספר"],
    ownerId: "u-tzachi",
    seedMetricId: null,
    submissionKey: "nps",
    entityType: null,
  },
  {
    key: "roi",
    titleHe: "החזר השקעה (ROI)",
    group: "ו",
    unit: "יחס",
    betterWhen: "higher",
    kind: "יעד פיילוט",
    temporality: "snapshot",
    sourceHe: "מחייב מדידת ערך ועלות בפועל — אף אחד מהם טרם נמדד",
    sourceCollections: [],
    calculationMethodHe: "ערך מדוד שנוצר ÷ עלות הטמעה מדודה",
    limitationsHe: ["הצגת ROI ללא מדידה היא בדיוק האנטי-דפוס שגל 7 נועד למנוע"],
    ownerId: "u-tzachi",
    seedMetricId: null,
    submissionKey: "roi",
    entityType: null,
  },
  {
    key: "time_saved_hours",
    titleHe: "זמן שנחסך בשבוע",
    group: "ו",
    unit: "שעות",
    betterWhen: "higher",
    kind: "יעד פיילוט",
    temporality: "snapshot",
    sourceHe: "מדידת זמן-למשימה בפיילוט — טרם החלה",
    sourceCollections: [],
    calculationMethodHe: "השוואת זמן-למשימה לפני/אחרי — מחייב מדידת קו בסיס",
    limitationsHe: ['הערכת "8 שעות/שבוע" מהדונור היא הצהרה — לא נמדדה ולא תוצג כערך'],
    ownerId: "u-tzachi",
    seedMetricId: null,
    submissionKey: "time_saved_hours",
    entityType: null,
  },
  {
    key: "customer_retention",
    titleHe: "שימור לקוחות",
    group: "ו",
    unit: "%",
    betterWhen: "higher",
    kind: "מבני",
    temporality: "snapshot",
    sourceHe: "אין הגדרת אירוע נטישה בנתונים — מוגדר בלבד",
    sourceCollections: [],
    calculationMethodHe: "לקוחות פעילים בסוף תקופה ÷ פעילים בתחילתה — אין תיעוד נטישה",
    limitationsHe: ["ללא הגדרת נטישה ותיעוד עזיבות אין דרך כנה למדוד"],
    ownerId: "u-tzachi",
    seedMetricId: null,
    submissionKey: null,
    entityType: null,
  },
  {
    key: "downtime",
    titleHe: "זמינות / השבתות מערכת",
    group: "ו",
    unit: "שעות",
    betterWhen: "lower",
    kind: "מבני",
    temporality: "snapshot",
    sourceHe: "אין טלמטריית זמינות — האפליקציה רצה מקומית בדפדפן",
    sourceCollections: [],
    calculationMethodHe: "שעות אי-זמינות בתקופה — אין מקור מדידה",
    limitationsHe: ["ללא ניטור זמינות אין נתון — לא מוצג מספר"],
    ownerId: "u-noa",
    seedMetricId: null,
    submissionKey: null,
    entityType: null,
  },
];

export function metricByKey(key: string): AnalyticsMetricDef | undefined {
  return ANALYTICS_METRICS.find((m) => m.key === key);
}

/** the honest split — computed once from the catalogue, never hardcoded */
export function catalogueSplit(): {
  computable: string[];
  pilotTargets: string[];
  structural: string[];
} {
  return {
    computable: ANALYTICS_METRICS.filter((m) => m.kind === "מחושב").map((m) => m.key),
    pilotTargets: ANALYTICS_METRICS.filter((m) => m.kind === "יעד פיילוט").map((m) => m.key),
    structural: ANALYTICS_METRICS.filter((m) => m.kind === "מבני").map((m) => m.key),
  };
}
