// Gate S4 — agents, governance, audit, metrics, adoption & comms mappings.
// Agent, AgentTask, AgentMessage, AgentHandoff, AIRecommendation, Evidence,
// AuditEvent, Automation, AutomationRun, MetricDefinition, MetricObservation,
// Persona, TrainingMaterial, ImplementationStage, StageGate, Meeting, Activity,
// AppNotification (collection "notifications").
import type {
  Activity,
  Agent,
  AgentHandoff,
  AgentMessage,
  AgentTask,
  AIRecommendation,
  AppNotification,
  AuditEvent,
  Automation,
  AutomationRun,
  Evidence,
  ImplementationStage,
  Meeting,
  MetricDefinition,
  MetricObservation,
  Persona,
  StageGate,
  TrainingMaterial,
} from "@/domain/types";
import {
  activitySchema,
  agentHandoffSchema,
  agentMessageSchema,
  agentSchema,
  agentTaskSchema,
  aiRecommendationSchema,
  auditEventSchema,
  automationRunSchema,
  automationSchema,
  evidenceSchema,
  implementationStageSchema,
  meetingSchema,
  metricDefinitionSchema,
  metricObservationSchema,
  notificationSchema,
  personaSchema,
  stageGateSchema,
  trainingMaterialSchema,
} from "@/domain/schemas";
import { defineMapping, fields, type AnyMapping } from "../mapping";

export const governanceAuditMappings: AnyMapping[] = [
  defineMapping<Agent>({
    collection: "agents",
    table: "agents",
    idPrefix: "ag",
    schema: agentSchema,
    fields: fields({
      name: "name",
      purpose: "purpose",
      allowedTools: "allowed_tools",
      allowedDomains: "allowed_domains",
      prohibitedDomains: "prohibited_domains",
      promptVersion: "prompt_version",
      limits: "limits",
      status: "status",
    }),
  }),
  defineMapping<AgentTask>({
    collection: "agentTasks",
    table: "agent_tasks",
    idPrefix: "at",
    schema: agentTaskSchema,
    fields: fields({
      agentId: "agent_id",
      title: "title",
      description: "description",
      status: "status",
      evidenceIds: "evidence_ids",
      approvalId: "approval_id",
    }),
  }),
  defineMapping<AgentMessage>({
    collection: "agentMessages",
    table: "agent_messages",
    idPrefix: "am",
    schema: agentMessageSchema,
    fields: fields({
      taskId: "task_id",
      fromAgentId: "from_agent_id",
      toAgentId: "to_agent_id",
      role: "role",
      content: "content",
      sentAt: "sent_at",
    }),
  }),
  defineMapping<AgentHandoff>({
    collection: "agentHandoffs",
    table: "agent_handoffs",
    idPrefix: "ah",
    schema: agentHandoffSchema,
    fields: fields({
      taskId: "task_id",
      fromAgentId: "from_agent_id",
      toAgentId: "to_agent_id",
      reason: "reason",
      contextSummary: "context_summary",
      at: "at",
    }),
  }),
  defineMapping<AIRecommendation>({
    collection: "aiRecommendations",
    table: "ai_recommendations",
    idPrefix: "rec",
    schema: aiRecommendationSchema,
    fields: fields({
      agentId: "agent_id",
      title: "title",
      reason: "reason",
      evidenceIds: "evidence_ids",
      confidenceMethod: "confidence_method",
      nextAction: "next_action",
      approvalRequired: "approval_required",
      approvalId: "approval_id",
      entityRef: "entity_ref",
    }),
  }),
  defineMapping<Evidence>({
    collection: "evidence",
    table: "evidence",
    idPrefix: "ev",
    schema: evidenceSchema,
    fields: fields({
      subjectRef: "subject_ref",
      sourceType: "source_type",
      sourceRef: "source_ref",
      claim: "claim",
      capturedAt: "captured_at",
    }),
  }),
  defineMapping<AuditEvent>({
    collection: "auditEvents",
    table: "audit_events",
    idPrefix: "au",
    schema: auditEventSchema,
    fields: fields({
      at: "at",
      actor: "actor",
      action: "action",
      entityRef: "entity_ref",
      details: "details",
      correlationId: "correlation_id",
    }),
  }),
  defineMapping<Automation>({
    collection: "automations",
    table: "automations",
    idPrefix: "auto",
    schema: automationSchema,
    fields: fields({
      name: "name",
      description: "description",
      trigger: "trigger",
      steps: "steps",
      enabled: "enabled",
      requiresApproval: "requires_approval",
    }),
  }),
  defineMapping<AutomationRun>({
    collection: "automationRuns",
    table: "automation_runs",
    idPrefix: "run",
    schema: automationRunSchema,
    fields: fields({
      automationId: "automation_id",
      startedAt: "started_at",
      endedAt: "ended_at",
      outcome: "outcome",
      stepsLog: "steps_log",
      triggeredBy: "triggered_by",
    }),
  }),
  defineMapping<MetricDefinition>({
    collection: "metricDefinitions",
    table: "metric_definitions",
    idPrefix: "md",
    schema: metricDefinitionSchema,
    fields: fields({
      key: "key",
      name: "name",
      level: "level",
      description: "description",
      unit: "unit",
      derivation: "derivation",
    }),
  }),
  defineMapping<MetricObservation>({
    collection: "metricObservations",
    table: "metric_observations",
    idPrefix: "mo",
    schema: metricObservationSchema,
    fields: fields({
      metricKey: "metric_key",
      observedAt: "observed_at",
      value: "value",
      method: "method",
    }),
  }),
  defineMapping<Persona>({
    collection: "personas",
    table: "personas",
    idPrefix: "ps",
    schema: personaSchema,
    fields: fields({
      name: "name",
      description: "description",
      mappedRole: "mapped_role",
      goals: "goals",
      painPoints: "pain_points",
      trainingTrack: "training_track",
    }),
  }),
  defineMapping<TrainingMaterial>({
    collection: "trainingMaterials",
    table: "training_materials",
    idPrefix: "tm",
    schema: trainingMaterialSchema,
    fields: fields({
      title: "title",
      description: "description",
      kind: "kind",
      audiencePersonaIds: "audience_persona_ids",
      url: "url",
      stageId: "stage_id",
    }),
  }),
  defineMapping<ImplementationStage>({
    collection: "implementationStages",
    table: "implementation_stages",
    idPrefix: "is",
    schema: implementationStageSchema,
    fields: fields({
      order: "order",
      name: "name",
      description: "description",
      status: "status",
      startPlanned: "start_planned",
      endPlanned: "end_planned",
      gateId: "gate_id",
    }),
  }),
  defineMapping<StageGate>({
    collection: "stageGates",
    table: "stage_gates",
    idPrefix: "sg",
    schema: stageGateSchema,
    fields: fields({
      order: "order",
      name: "name",
      criteria: "criteria",
      evidenceIds: "evidence_ids",
      status: "status",
      decidedAt: "decided_at",
      decidedById: "decided_by_id",
    }),
  }),
  defineMapping<Meeting>({
    collection: "meetings",
    table: "meetings",
    idPrefix: "mt",
    schema: meetingSchema,
    fields: fields({
      title: "title",
      scheduledAt: "scheduled_at",
      durationMinutes: "duration_minutes",
      location: "location",
      participantIds: "participant_ids",
      agenda: "agenda",
      relatedRef: "related_ref",
    }),
  }),
  defineMapping<Activity>({
    collection: "activities",
    table: "activities",
    idPrefix: "ac",
    schema: activitySchema,
    fields: fields({
      kind: "kind",
      text: "text",
      actorId: "actor_id",
      entityRef: "entity_ref",
      at: "at",
    }),
  }),
  defineMapping<AppNotification>({
    collection: "notifications",
    table: "app_notifications",
    idPrefix: "ntf",
    schema: notificationSchema,
    fields: fields({
      category: "category",
      title: "title",
      body: "body",
      relatedEntity: "related_entity",
      read: "read",
      severity: "severity",
      ownerId: "owner_id",
    }),
  }),
];
